version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.2.0
    container_name: graveyar_db_scylla
    restart: unless-stopped
    command: --seeds=scylla --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      - graveyar_net
    ports:
      - "9042:9042" # Native Transport
      - "19042:19042" # RPC Transport (mapped)

  graveyard-db:
    build: 
      context: ../../
      dockerfile: Dockerfile
    image: graveyar_db:local
    container_name: graveyar_db_app
    depends_on:
      - scylla
    environment:
      - SCYLLA_URI=scylla:9042
      - SCYLLA_KEYSPACE=graveyard
      - RUST_LOG=debug
      - DB_PATH=/data/rocksdb
    ports:
      - "50051:50051"
    networks:
      - graveyar_net
    volumes:
      - ../../src:/usr/src/app/src
      - ../../Cargo.toml:/usr/src/app/Cargo.toml

volumes:
  scylla-data:

networks:
  graveyar_net:
    driver: bridge
