// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: eventstore.proto

package eventstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AppendEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEventRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AppendEventRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AppendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventResponse) Reset() {
	*x = AppendEventResponse{}
	mi := &file_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventResponse) ProtoMessage() {}

func (x *AppendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventResponse.ProtoReflect.Descriptor instead.
func (*AppendEventResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

var File_eventstore_proto protoreflect.FileDescriptor

const file_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x10eventstore.proto\x12\n" +
	"eventstore\"n\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"\\\n" +
	"\x12AppendEventRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12)\n" +
	"\x06events\x18\x02 \x03(\v2\x11.eventstore.EventR\x06events\"/\n" +
	"\x13AppendEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10GetEventsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId2\x9c\x01\n" +
	"\n" +
	"EventStore\x12N\n" +
	"\vAppendEvent\x12\x1e.eventstore.AppendEventRequest\x1a\x1f.eventstore.AppendEventResponse\x12>\n" +
	"\tGetEvents\x12\x1c.eventstore.GetEventsRequest\x1a\x11.eventstore.Event0\x01B[\n" +
	"\x1bcom.eventstore.client.modelP\x01Z:github.com/riken127/graveyar_db/sdks/go/proto;eventstorepbb\x06proto3"

var (
	file_eventstore_proto_rawDescOnce sync.Once
	file_eventstore_proto_rawDescData []byte
)

func file_eventstore_proto_rawDescGZIP() []byte {
	file_eventstore_proto_rawDescOnce.Do(func() {
		file_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)))
	})
	return file_eventstore_proto_rawDescData
}

var file_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_eventstore_proto_goTypes = []any{
	(*Event)(nil),               // 0: eventstore.Event
	(*AppendEventRequest)(nil),  // 1: eventstore.AppendEventRequest
	(*AppendEventResponse)(nil), // 2: eventstore.AppendEventResponse
	(*GetEventsRequest)(nil),    // 3: eventstore.GetEventsRequest
}
var file_eventstore_proto_depIdxs = []int32{
	0, // 0: eventstore.AppendEventRequest.events:type_name -> eventstore.Event
	1, // 1: eventstore.EventStore.AppendEvent:input_type -> eventstore.AppendEventRequest
	3, // 2: eventstore.EventStore.GetEvents:input_type -> eventstore.GetEventsRequest
	2, // 3: eventstore.EventStore.AppendEvent:output_type -> eventstore.AppendEventResponse
	0, // 4: eventstore.EventStore.GetEvents:output_type -> eventstore.Event
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eventstore_proto_init() }
func file_eventstore_proto_init() {
	if File_eventstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventstore_proto_goTypes,
		DependencyIndexes: file_eventstore_proto_depIdxs,
		MessageInfos:      file_eventstore_proto_msgTypes,
	}.Build()
	File_eventstore_proto = out.File
	file_eventstore_proto_goTypes = nil
	file_eventstore_proto_depIdxs = nil
}
