apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graveyard-db.fullname" . }}-config
  labels:
    {{- include "graveyard-db.labels" . | nindent 4 }}
data:
  CLUSTER_NODES: {{ include "graveyard-db.clusterNodes" . | quote }}
