{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graveyard-db.authSecretName" . }}
  labels:
    {{- include "graveyard-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ include "graveyard-db.authToken" . | quote }}
{{- end }}
