// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: eventstore.proto

package eventstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType_Primitive int32

const (
	FieldType_NUMBER  FieldType_Primitive = 0
	FieldType_STRING  FieldType_Primitive = 1
	FieldType_BOOLEAN FieldType_Primitive = 2
)

// Enum value maps for FieldType_Primitive.
var (
	FieldType_Primitive_name = map[int32]string{
		0: "NUMBER",
		1: "STRING",
		2: "BOOLEAN",
	}
	FieldType_Primitive_value = map[string]int32{
		"NUMBER":  0,
		"STRING":  1,
		"BOOLEAN": 2,
	}
)

func (x FieldType_Primitive) Enum() *FieldType_Primitive {
	p := new(FieldType_Primitive)
	*p = x
	return p
}

func (x FieldType_Primitive) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType_Primitive) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_proto_enumTypes[0].Descriptor()
}

func (FieldType_Primitive) Type() protoreflect.EnumType {
	return &file_eventstore_proto_enumTypes[0]
}

func (x FieldType_Primitive) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType_Primitive.Descriptor instead.
func (FieldType_Primitive) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{8, 0}
}

// *
// Represents a single immutable event in the system.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of the event (e.g., "UserCreated", "OrderPlaced").
	// Used for schema validation and routing.
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// The actual event data, typically JSON serialized (or other formats).
	// Validated against Registered Schema if applicable.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Timestamp of when the event was created/appended (server side or client side).
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Key-Value metadata for context (e.g., TraceID, CausationID, SagaStep).
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Mandatory transition semantics for this event.
	// Every event must define the state movement it represents.
	Transition    *Transition `protobuf:"bytes,6,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

// *
// State transition represented by an event.
type Transition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transition name (e.g., "user.activated").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Previous state before this event was applied.
	FromState string `protobuf:"bytes,2,opt,name=from_state,json=fromState,proto3" json:"from_state,omitempty"`
	// Next state after this event was applied.
	ToState       string `protobuf:"bytes,3,opt,name=to_state,json=toState,proto3" json:"to_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *Transition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transition) GetFromState() string {
	if x != nil {
		return x.FromState
	}
	return ""
}

func (x *Transition) GetToState() string {
	if x != nil {
		return x.ToState
	}
	return ""
}

// *
// Request to append a batch of events to a specific stream.
type AppendEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the stream to append to (e.g., "user-123").
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// List of events to append.
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Expected version for Optimistic Concurrency Control (OCC).
	// - Use -1 to disable the version check.
	// - Use a non-negative version to require an exact match.
	ExpectedVersion int64 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	// Internal use: signals that this request was forwarded from another node.
	// Clients should generally set this to false.
	IsForwarded   bool `protobuf:"varint,4,opt,name=is_forwarded,json=isForwarded,proto3" json:"is_forwarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEventRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AppendEventRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AppendEventRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *AppendEventRequest) GetIsForwarded() bool {
	if x != nil {
		return x.IsForwarded
	}
	return false
}

type AppendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventResponse) Reset() {
	*x = AppendEventResponse{}
	mi := &file_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventResponse) ProtoMessage() {}

func (x *AppendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventResponse.ProtoReflect.Descriptor instead.
func (*AppendEventResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// *
// Defines the structure and constraints for an Event Type.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        map[string]*Field      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{5}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetFields() map[string]*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// *
// Defines a field within a Schema.
type Field struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FieldType *FieldType             `protobuf:"bytes,1,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	Nullable  bool                   `protobuf:"varint,2,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// If true, a null value in a partial update overrides the existing value.
	OverridesOnNull bool              `protobuf:"varint,3,opt,name=overrides_on_null,json=overridesOnNull,proto3" json:"overrides_on_null,omitempty"`
	Constraints     *FieldConstraints `protobuf:"bytes,4,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_eventstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{6}
}

func (x *Field) GetFieldType() *FieldType {
	if x != nil {
		return x.FieldType
	}
	return nil
}

func (x *Field) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Field) GetOverridesOnNull() bool {
	if x != nil {
		return x.OverridesOnNull
	}
	return false
}

func (x *Field) GetConstraints() *FieldConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// *
// Validation constraints for fields.
type FieldConstraints struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Required bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// Numeric constraints
	MinValue *float64 `protobuf:"fixed64,2,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"`
	MaxValue *float64 `protobuf:"fixed64,3,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"`
	// String constraints
	MinLength     *int32  `protobuf:"varint,4,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLength     *int32  `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	Regex         *string `protobuf:"bytes,6,opt,name=regex,proto3,oneof" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldConstraints) Reset() {
	*x = FieldConstraints{}
	mi := &file_eventstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints) ProtoMessage() {}

func (x *FieldConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{7}
}

func (x *FieldConstraints) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldConstraints) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *FieldConstraints) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *FieldConstraints) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *FieldConstraints) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *FieldConstraints) GetRegex() string {
	if x != nil && x.Regex != nil {
		return *x.Regex
	}
	return ""
}

// *
// Wrapper for field types, supporting primitives, enums, arrays, and nested schemas.
type FieldType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FieldType_Primitive_
	//	*FieldType_EnumDef
	//	*FieldType_SubSchema
	//	*FieldType_ArrayDef
	Kind          isFieldType_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType) Reset() {
	*x = FieldType{}
	mi := &file_eventstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType) ProtoMessage() {}

func (x *FieldType) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType.ProtoReflect.Descriptor instead.
func (*FieldType) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{8}
}

func (x *FieldType) GetKind() isFieldType_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FieldType) GetPrimitive() FieldType_Primitive {
	if x != nil {
		if x, ok := x.Kind.(*FieldType_Primitive_); ok {
			return x.Primitive
		}
	}
	return FieldType_NUMBER
}

func (x *FieldType) GetEnumDef() *FieldType_Enum {
	if x != nil {
		if x, ok := x.Kind.(*FieldType_EnumDef); ok {
			return x.EnumDef
		}
	}
	return nil
}

func (x *FieldType) GetSubSchema() *Schema {
	if x != nil {
		if x, ok := x.Kind.(*FieldType_SubSchema); ok {
			return x.SubSchema
		}
	}
	return nil
}

func (x *FieldType) GetArrayDef() *FieldType_Array {
	if x != nil {
		if x, ok := x.Kind.(*FieldType_ArrayDef); ok {
			return x.ArrayDef
		}
	}
	return nil
}

type isFieldType_Kind interface {
	isFieldType_Kind()
}

type FieldType_Primitive_ struct {
	Primitive FieldType_Primitive `protobuf:"varint,1,opt,name=primitive,proto3,enum=eventstore.FieldType_Primitive,oneof"`
}

type FieldType_EnumDef struct {
	EnumDef *FieldType_Enum `protobuf:"bytes,2,opt,name=enum_def,json=enumDef,proto3,oneof"`
}

type FieldType_SubSchema struct {
	SubSchema *Schema `protobuf:"bytes,3,opt,name=sub_schema,json=subSchema,proto3,oneof"`
}

type FieldType_ArrayDef struct {
	ArrayDef *FieldType_Array `protobuf:"bytes,4,opt,name=array_def,json=arrayDef,proto3,oneof"`
}

func (*FieldType_Primitive_) isFieldType_Kind() {}

func (*FieldType_EnumDef) isFieldType_Kind() {}

func (*FieldType_SubSchema) isFieldType_Kind() {}

func (*FieldType_ArrayDef) isFieldType_Kind() {}

type UpsertSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSchemaRequest) Reset() {
	*x = UpsertSchemaRequest{}
	mi := &file_eventstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSchemaRequest) ProtoMessage() {}

func (x *UpsertSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpsertSchemaRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertSchemaRequest) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type UpsertSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSchemaResponse) Reset() {
	*x = UpsertSchemaResponse{}
	mi := &file_eventstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSchemaResponse) ProtoMessage() {}

func (x *UpsertSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSchemaResponse.ProtoReflect.Descriptor instead.
func (*UpsertSchemaResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertSchemaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpsertSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_eventstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{11}
}

func (x *GetSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_eventstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{12}
}

func (x *GetSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetSchemaResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// *
// Represents a state snapshot of a stream.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_eventstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{13}
}

func (x *Snapshot) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Snapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Snapshot) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotRequest) Reset() {
	*x = SaveSnapshotRequest{}
	mi := &file_eventstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotRequest) ProtoMessage() {}

func (x *SaveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SaveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{14}
}

func (x *SaveSnapshotRequest) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SaveSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotResponse) Reset() {
	*x = SaveSnapshotResponse{}
	mi := &file_eventstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotResponse) ProtoMessage() {}

func (x *SaveSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SaveSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{15}
}

func (x *SaveSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_eventstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{16}
}

func (x *GetSnapshotRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_eventstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{17}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GetSnapshotResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type FieldType_Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variants      []string               `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType_Enum) Reset() {
	*x = FieldType_Enum{}
	mi := &file_eventstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType_Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType_Enum) ProtoMessage() {}

func (x *FieldType_Enum) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType_Enum.ProtoReflect.Descriptor instead.
func (*FieldType_Enum) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{8, 0}
}

func (x *FieldType_Enum) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

type FieldType_Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementType   *FieldType             `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType_Array) Reset() {
	*x = FieldType_Array{}
	mi := &file_eventstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType_Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType_Array) ProtoMessage() {}

func (x *FieldType_Array) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType_Array.ProtoReflect.Descriptor instead.
func (*FieldType_Array) Descriptor() ([]byte, []int) {
	return file_eventstore_proto_rawDescGZIP(), []int{8, 1}
}

func (x *FieldType_Array) GetElementType() *FieldType {
	if x != nil {
		return x.ElementType
	}
	return nil
}

var File_eventstore_proto protoreflect.FileDescriptor

const file_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x10eventstore.proto\x12\n" +
	"eventstore\"\xa0\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.eventstore.Event.MetadataEntryR\bmetadata\x126\n" +
	"\n" +
	"transition\x18\x06 \x01(\v2\x16.eventstore.TransitionR\n" +
	"transition\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\n" +
	"Transition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"from_state\x18\x02 \x01(\tR\tfromState\x12\x19\n" +
	"\bto_state\x18\x03 \x01(\tR\atoState\"\xaa\x01\n" +
	"\x12AppendEventRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12)\n" +
	"\x06events\x18\x02 \x03(\v2\x11.eventstore.EventR\x06events\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\x12!\n" +
	"\fis_forwarded\x18\x04 \x01(\bR\visForwarded\"/\n" +
	"\x13AppendEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10GetEventsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xa2\x01\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.eventstore.Schema.FieldsEntryR\x06fields\x1aL\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.eventstore.FieldR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x05Field\x124\n" +
	"\n" +
	"field_type\x18\x01 \x01(\v2\x15.eventstore.FieldTypeR\tfieldType\x12\x1a\n" +
	"\bnullable\x18\x02 \x01(\bR\bnullable\x12*\n" +
	"\x11overrides_on_null\x18\x03 \x01(\bR\x0foverridesOnNull\x12>\n" +
	"\vconstraints\x18\x04 \x01(\v2\x1c.eventstore.FieldConstraintsR\vconstraints\"\x99\x02\n" +
	"\x10FieldConstraints\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12 \n" +
	"\tmin_value\x18\x02 \x01(\x01H\x00R\bminValue\x88\x01\x01\x12 \n" +
	"\tmax_value\x18\x03 \x01(\x01H\x01R\bmaxValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\x04 \x01(\x05H\x02R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\x05 \x01(\x05H\x03R\tmaxLength\x88\x01\x01\x12\x19\n" +
	"\x05regex\x18\x06 \x01(\tH\x04R\x05regex\x88\x01\x01B\f\n" +
	"\n" +
	"_min_valueB\f\n" +
	"\n" +
	"_max_valueB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_lengthB\b\n" +
	"\x06_regex\"\x97\x03\n" +
	"\tFieldType\x12?\n" +
	"\tprimitive\x18\x01 \x01(\x0e2\x1f.eventstore.FieldType.PrimitiveH\x00R\tprimitive\x127\n" +
	"\benum_def\x18\x02 \x01(\v2\x1a.eventstore.FieldType.EnumH\x00R\aenumDef\x123\n" +
	"\n" +
	"sub_schema\x18\x03 \x01(\v2\x12.eventstore.SchemaH\x00R\tsubSchema\x12:\n" +
	"\tarray_def\x18\x04 \x01(\v2\x1b.eventstore.FieldType.ArrayH\x00R\barrayDef\x1a\"\n" +
	"\x04Enum\x12\x1a\n" +
	"\bvariants\x18\x01 \x03(\tR\bvariants\x1aA\n" +
	"\x05Array\x128\n" +
	"\felement_type\x18\x01 \x01(\v2\x15.eventstore.FieldTypeR\velementType\"0\n" +
	"\tPrimitive\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\v\n" +
	"\aBOOLEAN\x10\x02B\x06\n" +
	"\x04kind\"A\n" +
	"\x13UpsertSchemaRequest\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.eventstore.SchemaR\x06schema\"J\n" +
	"\x14UpsertSchemaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x10GetSchemaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"U\n" +
	"\x11GetSchemaResponse\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.eventstore.SchemaR\x06schema\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"y\n" +
	"\bSnapshot\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"G\n" +
	"\x13SaveSnapshotRequest\x120\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.eventstore.SnapshotR\bsnapshot\"0\n" +
	"\x14SaveSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x12GetSnapshotRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"]\n" +
	"\x13GetSnapshotResponse\x120\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x14.eventstore.SnapshotR\bsnapshot\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\xdc\x03\n" +
	"\n" +
	"EventStore\x12N\n" +
	"\vAppendEvent\x12\x1e.eventstore.AppendEventRequest\x1a\x1f.eventstore.AppendEventResponse\x12>\n" +
	"\tGetEvents\x12\x1c.eventstore.GetEventsRequest\x1a\x11.eventstore.Event0\x01\x12Q\n" +
	"\fUpsertSchema\x12\x1f.eventstore.UpsertSchemaRequest\x1a .eventstore.UpsertSchemaResponse\x12H\n" +
	"\tGetSchema\x12\x1c.eventstore.GetSchemaRequest\x1a\x1d.eventstore.GetSchemaResponse\x12Q\n" +
	"\fSaveSnapshot\x12\x1f.eventstore.SaveSnapshotRequest\x1a .eventstore.SaveSnapshotResponse\x12N\n" +
	"\vGetSnapshot\x12\x1e.eventstore.GetSnapshotRequest\x1a\x1f.eventstore.GetSnapshotResponseB[\n" +
	"\x1bcom.eventstore.client.modelP\x01Z:github.com/riken127/graveyar_db/sdks/go/proto;eventstorepbb\x06proto3"

var (
	file_eventstore_proto_rawDescOnce sync.Once
	file_eventstore_proto_rawDescData []byte
)

func file_eventstore_proto_rawDescGZIP() []byte {
	file_eventstore_proto_rawDescOnce.Do(func() {
		file_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)))
	})
	return file_eventstore_proto_rawDescData
}

var file_eventstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_eventstore_proto_goTypes = []any{
	(FieldType_Primitive)(0),     // 0: eventstore.FieldType.Primitive
	(*Event)(nil),                // 1: eventstore.Event
	(*Transition)(nil),           // 2: eventstore.Transition
	(*AppendEventRequest)(nil),   // 3: eventstore.AppendEventRequest
	(*AppendEventResponse)(nil),  // 4: eventstore.AppendEventResponse
	(*GetEventsRequest)(nil),     // 5: eventstore.GetEventsRequest
	(*Schema)(nil),               // 6: eventstore.Schema
	(*Field)(nil),                // 7: eventstore.Field
	(*FieldConstraints)(nil),     // 8: eventstore.FieldConstraints
	(*FieldType)(nil),            // 9: eventstore.FieldType
	(*UpsertSchemaRequest)(nil),  // 10: eventstore.UpsertSchemaRequest
	(*UpsertSchemaResponse)(nil), // 11: eventstore.UpsertSchemaResponse
	(*GetSchemaRequest)(nil),     // 12: eventstore.GetSchemaRequest
	(*GetSchemaResponse)(nil),    // 13: eventstore.GetSchemaResponse
	(*Snapshot)(nil),             // 14: eventstore.Snapshot
	(*SaveSnapshotRequest)(nil),  // 15: eventstore.SaveSnapshotRequest
	(*SaveSnapshotResponse)(nil), // 16: eventstore.SaveSnapshotResponse
	(*GetSnapshotRequest)(nil),   // 17: eventstore.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),  // 18: eventstore.GetSnapshotResponse
	nil,                          // 19: eventstore.Event.MetadataEntry
	nil,                          // 20: eventstore.Schema.FieldsEntry
	(*FieldType_Enum)(nil),       // 21: eventstore.FieldType.Enum
	(*FieldType_Array)(nil),      // 22: eventstore.FieldType.Array
}
var file_eventstore_proto_depIdxs = []int32{
	19, // 0: eventstore.Event.metadata:type_name -> eventstore.Event.MetadataEntry
	2,  // 1: eventstore.Event.transition:type_name -> eventstore.Transition
	1,  // 2: eventstore.AppendEventRequest.events:type_name -> eventstore.Event
	20, // 3: eventstore.Schema.fields:type_name -> eventstore.Schema.FieldsEntry
	9,  // 4: eventstore.Field.field_type:type_name -> eventstore.FieldType
	8,  // 5: eventstore.Field.constraints:type_name -> eventstore.FieldConstraints
	0,  // 6: eventstore.FieldType.primitive:type_name -> eventstore.FieldType.Primitive
	21, // 7: eventstore.FieldType.enum_def:type_name -> eventstore.FieldType.Enum
	6,  // 8: eventstore.FieldType.sub_schema:type_name -> eventstore.Schema
	22, // 9: eventstore.FieldType.array_def:type_name -> eventstore.FieldType.Array
	6,  // 10: eventstore.UpsertSchemaRequest.schema:type_name -> eventstore.Schema
	6,  // 11: eventstore.GetSchemaResponse.schema:type_name -> eventstore.Schema
	14, // 12: eventstore.SaveSnapshotRequest.snapshot:type_name -> eventstore.Snapshot
	14, // 13: eventstore.GetSnapshotResponse.snapshot:type_name -> eventstore.Snapshot
	7,  // 14: eventstore.Schema.FieldsEntry.value:type_name -> eventstore.Field
	9,  // 15: eventstore.FieldType.Array.element_type:type_name -> eventstore.FieldType
	3,  // 16: eventstore.EventStore.AppendEvent:input_type -> eventstore.AppendEventRequest
	5,  // 17: eventstore.EventStore.GetEvents:input_type -> eventstore.GetEventsRequest
	10, // 18: eventstore.EventStore.UpsertSchema:input_type -> eventstore.UpsertSchemaRequest
	12, // 19: eventstore.EventStore.GetSchema:input_type -> eventstore.GetSchemaRequest
	15, // 20: eventstore.EventStore.SaveSnapshot:input_type -> eventstore.SaveSnapshotRequest
	17, // 21: eventstore.EventStore.GetSnapshot:input_type -> eventstore.GetSnapshotRequest
	4,  // 22: eventstore.EventStore.AppendEvent:output_type -> eventstore.AppendEventResponse
	1,  // 23: eventstore.EventStore.GetEvents:output_type -> eventstore.Event
	11, // 24: eventstore.EventStore.UpsertSchema:output_type -> eventstore.UpsertSchemaResponse
	13, // 25: eventstore.EventStore.GetSchema:output_type -> eventstore.GetSchemaResponse
	16, // 26: eventstore.EventStore.SaveSnapshot:output_type -> eventstore.SaveSnapshotResponse
	18, // 27: eventstore.EventStore.GetSnapshot:output_type -> eventstore.GetSnapshotResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_eventstore_proto_init() }
func file_eventstore_proto_init() {
	if File_eventstore_proto != nil {
		return
	}
	file_eventstore_proto_msgTypes[7].OneofWrappers = []any{}
	file_eventstore_proto_msgTypes[8].OneofWrappers = []any{
		(*FieldType_Primitive_)(nil),
		(*FieldType_EnumDef)(nil),
		(*FieldType_SubSchema)(nil),
		(*FieldType_ArrayDef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventstore_proto_rawDesc), len(file_eventstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventstore_proto_goTypes,
		DependencyIndexes: file_eventstore_proto_depIdxs,
		EnumInfos:         file_eventstore_proto_enumTypes,
		MessageInfos:      file_eventstore_proto_msgTypes,
	}.Build()
	File_eventstore_proto = out.File
	file_eventstore_proto_goTypes = nil
	file_eventstore_proto_depIdxs = nil
}
